
package module.webservice.services.example3.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://example3.services.webservice.module/")
public class Exception_Exception extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, Exception faultInfo) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, Exception faultInfo, Throwable cause) {
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: module.webservice.services.example.client.Exception
     */
    public Exception getFaultInfo() {
        return faultInfo;
    }

}
