
package module.webservice.services.example3.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RabbitCounter", targetNamespace = "http://example3.services.webservice.module/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RabbitCounter {


    /**
     *
     * @param arg0
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countRabbits", targetNamespace = "http://example3.services.webservice.module/", className = "module.webservice.services.example.client.CountRabbits")
    @ResponseWrapper(localName = "countRabbitsResponse", targetNamespace = "http://example3.services.webservice.module/", className = "module.webservice.services.example.client.CountRabbitsResponse")
    @Action(input = "http://example3.services.webservice.module/RabbitCounter/countRabbitsRequest", output = "http://example3.services.webservice.module/RabbitCounter/countRabbitsResponse", fault = {
    })
    public int countRabbits(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0)
        throws Exception_Exception
    ;

}
