
package module.webservice.services.example2.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Teams", targetNamespace = "http://example2.services.webservice.module/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Teams {


    /**
     * 
     * @return
     *     returns java.util.List<module.webservice.services.example2.client.Team>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://example2.services.webservice.module/", className = "module.webservice.services.example2.client.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://example2.services.webservice.module/", className = "module.webservice.services.example2.client.GetTeamsResponse")
    @Action(input = "http://example2.services.webservice.module/Teams/getTeamsRequest", output = "http://example2.services.webservice.module/Teams/getTeamsResponse")
    public List<Team> getTeams();

    /**
     * 
     * @param arg0
     * @return
     *     returns module.webservice.services.example2.client.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeam", targetNamespace = "http://example2.services.webservice.module/", className = "module.webservice.services.example2.client.GetTeam")
    @ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://example2.services.webservice.module/", className = "module.webservice.services.example2.client.GetTeamResponse")
    @Action(input = "http://example2.services.webservice.module/Teams/getTeamRequest", output = "http://example2.services.webservice.module/Teams/getTeamResponse")
    public Team getTeam(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
