
DROP TABLE IF EXISTS ST_CLUSTER_CONTROL;

CREATE TABLE ST_CLUSTER_CONTROL(
  TASK_NAME VARCHAR(50) UNIQUE COMMENT 'TASK BEAN ID',
  TASK_STATUS VARCHAR(20) DEFAULT 'WAIT' COMMENT 'WAIT, RUNNING,COMPLETED,FAILED',
  TASK_LOCK INT DEFAULT 1 COMMENT '1 WAIT, 2 PROCESSING',
  TASK_GROUP VARCHAR(50) DEFAULT NULL COMMENT 'TASK THREAD GROUP',
  TASK_CLASS_NAME VARCHAR(100) DEFAULT NULL COMMENT 'TASK CLASS NAME',
  SCHEDULE_NAME VARCHAR(50) DEFAULT NULL COMMENT 'EXECUTOR NAME',
  LAST_START_TIME TIMESTAMP COMMENT 'START TIME',
  LAST_END_TIME TIMESTAMP COMMENT 'END TIME',
  PRIMARY KEY (TASK_NAME)
)DEFAULT CHARSET =utf8