
DROP TABLE ST_JOB_CONTROL;
DROP TABLE ST_TASK_CONTROL;

CREATE TABLE ST_TASK_CONTROL(
  TASK_NAME VARCHAR2(50) UNIQUE,
  TASK_STATUS VARCHAR2(20) DEFAULT 'WAIT',
  TASK_LOCK INT DEFAULT 1 ,
  TASK_GROUP VARCHAR2(50) DEFAULT NULL,
  TASK_CLASS_NAME VARCHAR2(100) DEFAULT NULL,
  SCHEDULE_NAME VARCHAR2(50) DEFAULT NULL,
  LAST_START_TIME TIMESTAMP,
  LAST_END_TIME TIMESTAMP
);

CREATE TABLE ST_JOB_CONTROL(
  JOB_NAME VARCHAR(50) UNIQUE ,
  JOB_STATUS VARCHAR(20) DEFAULT 'WAIT', 
  JOB_LOCK INT DEFAULT 1 ,
  JOB_GROUP VARCHAR(50) DEFAULT NULL ,
  JOB_CLASS_NAME VARCHAR(100) DEFAULT NULL,
  SCHEDULE_NAME VARCHAR(200) DEFAULT NULL,
  LAST_START_TIME TIMESTAMP,
  LAST_END_TIME TIMESTAMP
);